# Use Docker environment
sudo: false

# Setup build matrix
language: php
php:
  - 5.4
  - 5.6
  - 7.0
  - 7.1

script:
  - travis_retry composer install --no-interaction --prefer-dist
  - composer lint -- --dry-run
